### ISSUE TITLE
Merge request #null Created

### ISSUE THREAD

**Issue by slava-oxgaming** [novotnyr/gitlab-quickmr-idea-plugin#22]
![image](https://user-images.githubusercontent.com/46717640/72807061-365f5b00-3c5f-11ea-9757-62bef8dac505.png)

I am trying to create a merge request but I am receiving this answer. And Merge Request doesn't appear

**Comment by novotnyr** [comment]
This might be connected with NPE.

```
ava.lang.NullPointerException
	at java.base/java.net.URI$Parser.parse(URI.java:3104)
	at java.base/java.net.URI.<init>(URI.java:600)
	at com.github.novotnyr.idea.gitlab.quickmr.CreateMergeRequestAction$2.hyperlinkUpdate(CreateMergeRequestAction.java:163)
	at com.intellij.notification.EventLog$NotificationHyperlinkInfo.navigate(EventLog.java:582)
	at com.intellij.execution.impl.EditorHyperlinkSupport.lambda$getLinkNavigationRunnable$0(EditorHyperlinkSupport.java:155)
	at com.intellij.execution.impl.EditorHyperlinkSupport$1.mouseReleased(EditorHyperlinkSupport.java:84)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.runMouseReleasedCommand(EditorImpl.java:3790)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseReleased(EditorImpl.java:3693)
```

**Comment by slava-oxgaming** [comment]
Can I know reason for an exception?

**Comment by slava-oxgaming** [comment]
![image](https://user-images.githubusercontent.com/46717640/72814441-b8ef1700-3c6d-11ea-9223-31844fcbafcb.png)

**Comment by novotnyr** [comment]
@slava-oxgaming This might happen if your GitLab project remote does not match the GitLab URL in _Preferences_.

Please check the `git remote -v` output and compare it to the GitLab URL in plugin configuration.

I was able to reproduce this, when

1.  `git remote -v` showed:
    
    ```
    origin	git@gitlab.com:novotnyr/dummy-project.git (fetch)
    origin	git@gitlab.com:novotnyr/dummy-project.git (push)
    ```
2.  GitLab URI was `http://localhost/api/v4`.

These two URLs do not match, hence the error.

I have improved the error handling to cover this scenario on a separate branch.
