### ISSUE TITLE
Unable to load last commit message when the working directory is not a git directory

### ISSUE THREAD

**Issue by learnting** [novotnyr/gitlab-quickmr-idea-plugin#35]
idea working directory e.g.
- C:\core
   - module_a   a git directory
   - module_b   another git dircetory

when I create a merge request of module_a, an error is reported
error log:
```
Unable to load last commit message

git4idea.GitUtil$GitRepositoryNotFoundException: Can't find configured git repository for C:\core
	at git4idea.GitUtil.getRootForFile(GitUtil.java:691)
	at git4idea.history.GitHistoryUtils.getCurrentRevisionDescription(GitHistoryUtils.java:209)
	at com.github.novotnyr.idea.git.GitService.getLastCommitMessage(GitService.java:84)
	at com.github.novotnyr.idea.gitlab.quickmr.PlaceholderResolver.resolvePlaceholder(PlaceholderResolver.java:32)
	at com.github.novotnyr.idea.gitlab.quickmr.MergeRequestService.resolvePlaceHolders(MergeRequestService.java:76)
	at com.github.novotnyr.idea.gitlab.quickmr.MergeRequestService.setTitle(MergeRequestService.java:56)
	at com.github.novotnyr.idea.gitlab.quickmr.MergeRequestService.prepare(MergeRequestService.java:38)
	at com.github.novotnyr.idea.gitlab.quickmr.CreateMergeRequestAction.createMergeRequestAsync(CreateMergeRequestAction.java:81)
	at com.github.novotnyr.idea.gitlab.quickmr.CreateMergeRequestAction.lambda$actionPerformed$0(CreateMergeRequestAction.java:64)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at com.github.novotnyr.idea.gitlab.quickmr.CreateMergeRequestAction.lambda$getProjectName$3(CreateMergeRequestAction.java:173)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:270)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by learnting** [comment]
I tested it
```java
    GitHistoryUtils.getCurrentRevisionDescription(
        selectedModule.getProject(),
        VcsUtil.getFilePath(VcsUtil.getVcsRootFor(selectedModule.getProject(), selectedModule.getFile()))
    ).getCommitMessage();
```
the above method can solve this bug, hope it can help you

**Comment by learnting** [comment]
I have a new discovery, **getCurrentRevisionDescription** will find the latest commit message in all branches, including remote branches. If the local branch is submitted earlier than the remote branch, the behavior of **getCurrentRevisionDescription** is inconsistent with the expected
