### ISSUE TITLE
CreateMergeRequestAndAssignToActionGroup must override getActionUpdateThread()

### ISSUE THREAD

**Issue by usmanovbf** [novotnyr/gitlab-quickmr-idea-plugin#65]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.novotnyr.idea.gitlab.quickmr.CreateMergeRequestAndAssignToActionGroup' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.github.novotnyr.gitlab-quickmr-idea-plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

IntelliJ IDEA 2024.2.3 (Ultimate Edition)
Build #IU-242.23339.11, built on September 25, 2024

**Comment by novotnyr** [comment]
Resolved in v28.
